### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by Neutrideo** [CircleBilling/CircleBilling#10]
Hey, I want to get this, But How do I download it. I want to start hosting cpanel hosting.

**Comment by Eiskaltereistee** [comment]
Hi @Neutrideo,
currently, there is no downloadable available. 

We're currently working on a stable and working version (Have a look at our development branch).

You can get and install that version (But please not that it's not stable):
`git clone https://github.com/CircleBilling/CircleBilling --branch develop`
Then change to the main directory and run:
`composer install` 
Maybe you need to install composer first: 
- apt install composer,
- yum install composer, 
- yast install composer

After that you can install CircleBilling with the web installer.

Maybe you can use php7.2 and please report any issue, you can find. We're very active in development and would be happy to get some feedback!

Thank you!

**Comment by Neutrideo** [comment]
Thank you, But I am currently on shared reseller hosting

**Comment by Eiskaltereistee** [comment]
@Neutrideo then you can install php7 and composer on your PC, checkout the git and install the dependencies locally. Then simply upload the files via ftp. I think that should work.

Otherwise you can use our vagrant vm: 
- Clone git
- Run vagrant up
- Connect via ssh to vagrant vm (vagrant ssh)
- "apt install composer"
- goto "/var/www/circlebilling.local" and run "composer install"

Because of the synced folder, you should be able to uplode the files via FTP.

A other option is, that you wait about 1 week. I hope we can release our first version then.

**Comment by StefvanEgmond** [comment]
Don't use the support tickets for that, thanks!

> Any news about stable?
